load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "test",
    srcs = ["test.c"],
    deps = [
        "@com_github_dio_icuuc//:common",
        "@com_github_dio_icuuc//:data",
    ],
)
